# 資料前處理(Label encoding、 One hot encoding)
這兩個編碼方式的目的是為了將類別 (categorical)或是文字(text)的資料轉換成數字，而讓程式能夠更好的去理解及運算。
> Label encoding : 把每個類別 mapping 到某個整數，不會增加新欄位

> One hot encoding : 為每個類別新增一個欄位，用 0/1 表示是否

![](images/Encoder.PNG)


## Encoding Categorical features (or label)
![](images/Encoding.PNG)

In [3]:
%pip install pandas numpy scikit-learn tensorflow keras

Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (2.4.6)
Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp311-cp311-macosx_12_0_arm64.whl.metadata (9.3 kB)
Requirement already satisfied: tensorflow in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (2.21.0)
Requirement already satisfied: keras in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (3.15.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: absl-py>=1.0.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: astunparse>=1.6.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: rich in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (15.0.0)
Requirement already satisfied: namex in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.1.0)
Requirement already satisfied: optree in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.20.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from rich->keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from rich->keras) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Downloading pandas-3.0.6-cp311-cp311-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 16.9 MB/s  0:00:0017.6 MB/s eta 0:00:01
Downloading scikit_learn-1.9.1-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 17.6 MB/s  0:00:007.6 MB/s eta 0:00:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 15.7 MB/s  0:00:01a 0:00:01m eta 0:00:01
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, pandas, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [scikit-learn]0m 6/7 [scikit-learn]]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.27.1 pandas-3.0.6 scikit-learn-1.9.1 scipy-1.17.1 threadpoolctl-3.7.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});
df

  blood     Y       Z
0     A  high     NaN
1     B   low     NaN
2    AB  high -1196.0
3     O   mid    72.0
4     B   mid    83.0

# 方法一：sklearn - label encoder + onehot encoder
>onehot encoder要用2D array，若維度所以要用reshape(-1,1)<br>
>onehot encoder要數字，若資料文文字要先用label encoder轉數字

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(df['blood'])
print(encoded_Y)
df['blood'] = encoded_Y
df

[0 2 1 3 2]

   blood     Y       Z
0      0  high     NaN
1      2   low     NaN
2      1  high -1196.0
3      3   mid    72.0
4      2   mid    83.0

In [6]:
#from sklearn.preprocessing improt OneHotEncoder
import sklearn.preprocessing as preprocessing
onehot = preprocessing.OneHotEncoder()
#print(type(df['blood']))
d = np.array(df['blood'])
d.shape
onehot_df = onehot.fit_transform(d.reshape(-1,1)).toarray()
onehot_df

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

## One hot encoding
One Hot encoding的編碼邏輯為將類別拆成多個行(column)，每個列中的數值由1、0替代，當某一列的資料存在的該行的類別則顯示1，反則顯示0。

然在指定column進行編碼的情形下，One hot encoding<b>無法直接對字串進行編碼，必須先透過Label encoding將字串以數字取代後再進行One hot encoding處理。</b>

> categorical_features = [0]: 表示欲在data上執行One hot encoding的index為0

> data_le: 為經過Label encoding編碼的資料(註:OneHotEncoder的輸入要為2-D array，而Label encoding為1-D array)

OneHotEncoder會轉出scipy.csr_matrix資料結構用.toarray()轉array
從結果可以知道，數字0的column 代表的是A、數字1的column 代表的是B，而數字2的column 代表的是AB。
除了轉換字串外，One hot encoding也可以轉換數字。在此處的data就不需要先經過Label encoding編碼

```python
# importing one hot encoder from sklearn 
# There are changes in OneHotEncoder class 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 
   
# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough') 
  
data = np.array(columnTransformer.fit_transform(data), dtype = str) 
```

In [7]:
# importing one hot encoder from sklearn 
# There are changes in OneHotEncoder class 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])],
                                      remainder='passthrough') 

data = np.array(columnTransformer.fit_transform(df),dtype=str)
data

data_le = pd.DataFrame(data)
data_le

     0    1    2    3     4        5
0  1.0  0.0  0.0  0.0  high      nan
1  0.0  0.0  1.0  0.0   low      nan
2  0.0  1.0  0.0  0.0  high  -1196.0
3  0.0  0.0  0.0  1.0   mid     72.0
4  0.0  0.0  1.0  0.0   mid     83.0

In [7]:
%pip install --upgrade keras

Requirement already satisfied: keras in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (3.15.1)
Requirement already satisfied: absl-py in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (2.5.1)
Requirement already satisfied: numpy in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (2.4.6)
Requirement already satisfied: rich in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (15.0.0)
Requirement already satisfied: namex in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (3.14.0)
Requirement already satisfied: optree in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.20.0)
Requirement already satisfied: ml-dtypes in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.6.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from optree->keras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from rich->keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from rich->keras) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

# 方法二：Keras - label encoder + to_categorical
>to_categorical要數字，若資料文文字要先用label encoder轉數字

In [8]:

from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});

# label encoder 
encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(df['blood'])
df['blood'] = encoded_Y
df

# convert integers to one hot encoding
keras_onehot = to_categorical(encoded_Y) 
keras_onehot

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

## 方法三：pd.get_dummies方法
![](images/Encoding_pd.PNG)
pd.get_dummies(df)
>get_dummies可以直接轉字串，反而無法轉換數字<br>
>get_dummies沒指定columns，會全部轉換

In [15]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'],
                  'Y':['high','low','high','mid','mid'],
                  'Z':[np.nan,np.nan,-1196,72,83]})
df1 = pd.get_dummies(df)
print(df1)

df2 = pd.get_dummies(df.blood)
print(df2)

        Z  blood_A  blood_AB  blood_B  blood_O  Y_high  Y_low  Y_mid
0     NaN     True     False    False    False    True  False  False
1     NaN    False     False     True    False   False   True  False
2 -1196.0    False      True    False    False    True  False  False
3    72.0    False     False    False     True   False  False   True
4    83.0    False     False     True    False   False  False   True
       A     AB      B      O
0   True  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False   True
4  False  False   True  False

## 練習一：sklearn - label encoder + onehot encoder
下面的資料可以看到country那欄皆為字串， 大部分的模型都是基於數學運算，字串無法套入數學模型進行運算，<br>
在此先對其進行Label encoding編碼，我們從 sklearn library中導入 LabelEncoder class，對第一行資料進行fit及transform並取代之。

In [10]:
import numpy as np
import pandas as pd
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data

     Country  Age  Salary
0     Taiwan   25   20000
1  Australia   30   32000
2    Ireland   45   59000
3  Australia   35   60000
4    Ireland   22   43000
5     Taiwan   36   52000

## 練習二：Keras - label encoder + to_categorical

In [12]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data

     Country  Age  Salary
0     Taiwan   25   20000
1  Australia   30   32000
2    Ireland   45   59000
3  Australia   35   60000
4    Ireland   22   43000
5     Taiwan   36   52000

## 練習三：Pandas.get_dummies
>　get_dummies : 僅能將字串轉換為One hot encoding表示形式， 沒指定columns會全部轉換。

In [19]:
# df = pd.DataFrame({'blood':['A','B','AB','O','B'],
#                   'Y':['high','low','high','mid','mid'],
#                   'Z':[np.nan,np.nan,-1196,72,83]})
# df1 = pd.get_dummies(df)
# print(df1)

# df2 = pd.get_dummies(df.blood)
# print(df2)
country = ['Taiwan', 'Australia', 'Ireland',
           'Australia', 'Ireland', 'Taiwan']

age = [25, 30, 45, 35, 22, 36]

salary = [20000, 32000, 59000, 60000, 43000, 52000]

dic = {
    'Country': country,
    'Age': age,
    'Salary': salary
}

data = pd.DataFrame(dic)
data1 = pd.get_dummies(data)
print(data1)

data2 = pd.get_dummies(data.Country)
print(data2)

   Age  Salary  Country_Australia  Country_Ireland  Country_Taiwan
0   25   20000              False            False            True
1   30   32000               True            False           False
2   45   59000              False             True           False
3   35   60000               True            False           False
4   22   43000              False             True           False
5   36   52000              False            False            True
   Australia  Ireland  Taiwan
0      False    False    True
1       True    False   False
2      False     True   False
3       True    False   False
4      False     True   False
5      False    False    True

In [ ]:
!conda create -n keras311 python=3.11 -y

In [5]:
!/opt/anaconda3/envs/keras311/bin/python -m pip install tensorflow keras ipykernel

Requirement already satisfied: tensorflow in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (2.21.0)
Requirement already satisfied: keras in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (3.15.1)
Requirement already satisfied: ipykernel in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (7.4.0)
Requirement already satisfied: absl-py>=1.0.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: astunparse>=1.6.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (2.4.6)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: rich in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (15.0.0)
Requirement already satisfied: namex in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.1.0)
Requirement already satisfied: optree in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from keras) (0.20.0)
Requirement already satisfied: appnope>=0.1.2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (1.0.0)
Requirement already satisfied: comm>=0.1.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (1.8.22)
Requirement already satisfied: ipython>=7.23.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (9.17.1)
Requirement already satisfied: jupyter-client>=8.9.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (8.10.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (1.7.4)
Requirement already satisfied: pyzmq>=25 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (27.2.0)
Requirement already satisfied: tornado>=6.5.7 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (6.5.10)
Requirement already satisfied: traitlets>=5.4.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipykernel) (5.16.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (0.20.1)
Requirement already satisfied: pexpect>4.6 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (3.0.53)
Requirement already satisfied: psutil>=7 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.9.2)
Requirement already satisfied: parso<0.9.0,>=0.8.7 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from jupyter-client>=8.9.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.13.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from pexpect>4.6->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.3.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.2)
Requirement already satisfied: pure-eval in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from rich->keras) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/keras311/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

In [7]:
!/opt/anaconda3/envs/keras311/bin/python -m ipykernel install --user --name keras311 --display-name "Python 3.11 (Keras)"

Installed kernelspec keras311 in /Users/liangzhezhi/Library/Jupyter/kernels/keras311